"""add server default values in access_roles_rules table

Revision ID: 8f74f49c81b0
Revises: 85d2f859db5b
Create Date: 2026-03-27 19:31:08.545619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f74f49c81b0'
down_revision: Union[str, Sequence[str], None] = '85d2f859db5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('access_roles_rules', 'read_permission',
               existing_type=sa.BOOLEAN(),
               server_default='true',
               existing_nullable=False)
    op.alter_column('access_roles_rules', 'read_all_permission',
               existing_type=sa.BOOLEAN(),
               server_default='true',
               existing_nullable=False)
    op.alter_column('access_roles_rules', 'create_permission',
               existing_type=sa.BOOLEAN(),
               server_default='false',
               existing_nullable=False)
    op.alter_column('access_roles_rules', 'update_permission',
               existing_type=sa.BOOLEAN(),
               server_default='false',
               existing_nullable=False)
    op.alter_column('access_roles_rules', 'update_all_permission',
               existing_type=sa.BOOLEAN(),
               server_default='false',
               existing_nullable=False)
    op.alter_column('access_roles_rules', 'delete_permission',
               existing_type=sa.BOOLEAN(),
               server_default='false',
               existing_nullable=False)
    op.alter_column('access_roles_rules', 'delete_all_permission',
               existing_type=sa.BOOLEAN(),
               server_default='false',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('access_roles_rules', 'delete_all_permission',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('access_roles_rules', 'delete_permission',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('access_roles_rules', 'update_all_permission',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('access_roles_rules', 'update_permission',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('access_roles_rules', 'create_permission',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('access_roles_rules', 'read_all_permission',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('access_roles_rules', 'read_permission',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###
