"""create unique constraint for role_id and element_id

Revision ID: 85d2f859db5b
Revises: ccfddf304a04
Create Date: 2026-03-27 19:17:49.321934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85d2f859db5b'
down_revision: Union[str, Sequence[str], None] = 'ccfddf304a04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_role_element', 'access_roles_rules', ['role_id', 'element_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_role_element', 'access_roles_rules', type_='unique')
    # ### end Alembic commands ###
